version: "3"
services:
  rabbitmq:
    image: rabbitmq
  dao:
    build: .
    image: celery_dao:latest
    ports:
      - 8000:8000
    links:
      - rabbitmq
    volumes:
      - appvolume:/src
    depends_on:
      - rabbitmq
      - worker
  worker:
    build: .
    image: celery_dao:latest
    command: celery -A celery_dao.celery:worker worker --loglevel=info
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    volumes:
      - appvolume:/src

volumes:
     appvolume: {}